services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: os.getenv('POSTGRES_USER')
      POSTGRES_PASSWORD: os.getenv('POSTGRES_PASSWORD')
      POSTGRES_DB: os.getenv('POSTGRES_DB')
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

